version: '3'
services:
  cmake:
    build: .
    container_name: auto_sklearn
    ports:
      - "8080:8080"
    volumes:
      - .:/home/project
    tty: true
    networks:
      static-network:
        ipv4_address: 172.41.12.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.41.0.0/16
          #docker-compose v3+ do not use ip_range
          # ip_range: 192.168.0.1/24
